PS1.-ChavezLopezEduardoGuillermo/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS1._ChavezLopezEduardoGuillermo.Models;

namespace PS1._ChavezLopezEduardoGuillermo.Controllers
{
    public class CitiesController : Controller
    {
        private EventDbContext db = new EventDbContext();

        // GET: Cities
        public ActionResult Index()
        {
            return View(db.Cities.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NombreCiudad,Poblacion,Estado,Pais")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NombreCiudad,Poblacion,Estado,Pais")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS1.-ChavezLopezEduardoGuillermo/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS1._ChavezLopezEduardoGuillermo.Models;

namespace PS1._ChavezLopezEduardoGuillermo.Controllers
{
    public class EventsController : Controller
    {
        private EventDbContext db = new EventDbContext();

        // GET: Events
        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NombreEvento,FechaInicio,FechaFinal,TipoEvento,Capacidad")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NombreEvento,FechaInicio,FechaFinal,TipoEvento,Capacidad")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS1.-ChavezLopezEduardoGuillermo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PS1._ChavezLopezEduardoGuillermo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PS1.-ChavezLopezEduardoGuillermo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>Acerca de la pagina</h2>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Informacion sobre la practica</h3>
    </div>
    <div class="panel-body">
        <p>
            Esta practica consiste en desarrollar una pagina que genere tablas de eventos y ciudades;
            cada tabla debe contener los variables necesarias para alvergar los datos y deben de ser los suficientes
            para complementar la informacion requerida, ademas de ello, personalizar un poco la pagina y sea presentable.
        </p>
    </div>
</div>

PS1.-ChavezLopezEduardoGuillermo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Contacto</h2>
<img src="~/Content/img/Mi foto.jpg" width="250" height="250">
<h3>Informacion</h3>

<address>
    <span class="glyphicon glyphicon-user"></span><strong>Nombre:</strong>
    <p>Chavez Lopez Eduardo Guillermo</p>
    <span class="glyphicon glyphicon-pencil"></span><strong>Carrera:</strong>
    <p>Ingenieria en Informatica</p>
    <span class="glyphicon glyphicon-calendar"></span><strong>Semestre:</strong>
    <p>6to</p>
    <span class="glyphicon glyphicon-asterisk"></span><strong>Numero de control:</strong>
    <p>17212334</p>
    <span class="glyphicon glyphicon-envelope"></span><strong>Correo Electronico:</strong> <a href="mailto:eduardo.chavez17@tectijuana.edu.mx">eduardo.chavez17@tectijuana.edu.mx</a><br />
    <br /><span class="glyphicon glyphicon-earphone"></span><strong>Numero de Telefono:</strong> 664-178-89-70
</address>

PS1.-ChavezLopezEduardoGuillermo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1 class="text-center">Practica Semanal 01</h1>
    <p class="lead text-center">Desarrollo de Aplicaciones Web</p>
    
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Eventos</h2>
        <p>
            Los eventos son parte importante del desarrollo cultural y social de una entidad poblacional
            ya que puede generar felicidad en las masas, ayudas sociales, actividades de caridad y un largo
            etc que ayuda al crecimiento de una ciudad.
        </p>
        <img src="~/Content/img/Evento.jpg" width="300" height="200">
        <p><a class="btn btn-primary" @Html.ActionLink("Eventos", "Index", "Events")></a></p>
    </div>
    <div class="col-md-4">
        <h2>Ciudades</h2>
        <p>
            Para que surja un gran evento tiene que realizarse en una ciudad que haga relucir ese mismo evento,
            para ello, la ciudad debe de aceptar el evento y almismo tiempo, comprometerse con el.
        </p>
        <img src="~/Content/img/Ciudad.jpg" width="300" height="200">
        <p><a class="btn btn-primary" @Html.ActionLink("Ciudades", "Index", "Cities")></a></p>
    </div>
    <div class="col-md-4">
        <h2>Sobre mi</h2>
        <p>
            Mucho gusto, soy Chavez Lopez Eduardo Guillermo y esta pagina fue elaborada por mi
            si quieres contactarme o saber mas de mi, dirigete a la seccon de contacto.
        </p>
        <img src="~/Content/img/Mi foto.jpg" width="200" height="200">
        <p><a class="btn btn-primary" @Html.ActionLink("Contacto", "Contact", "Home")></a></p>
    </div>
</div>